/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_retina_demo_RetinaServiceImpl */

#ifndef _Included_com_retina_demo_RetinaServiceImpl
#define _Included_com_retina_demo_RetinaServiceImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_retina_demo_RetinaServiceImpl
 * Method:    updateRecord
 * Signature: (Lcom/retina/demo/UpdateRecordOptions;)Z
 */
JNIEXPORT jboolean JNICALL
Java_com_retina_demo_RetinaServiceImpl_updateRecord(JNIEnv *, jobject, jobject);

/*
 * Class:     com_retina_demo_RetinaServiceImpl
 * Method:    insertRecord
 * Signature: (Lcom/retina/demo/InsertRecordOptions;)Z
 */
JNIEXPORT jboolean JNICALL
Java_com_retina_demo_RetinaServiceImpl_insertRecord(JNIEnv *, jobject, jobject);

/*
 * Class:     com_retina_demo_RetinaServiceImpl
 * Method:    deleteRecord
 * Signature: (Lcom/retina/demo/DeleteRecordOptions;)Z
 */
JNIEXPORT jboolean JNICALL
Java_com_retina_demo_RetinaServiceImpl_deleteRecord(JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
